# Generated by Django 3.1.14 on 2022-01-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ph1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ph2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='temp1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='id',
        ),
        migrations.AlterField(
            model_name='ph1',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ph2',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temp1',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temp2',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
