version: '3.8'

services:
  web:
    build: .
    command: /bin/sh -c /code/entrypoint.dev.sh
    volumes:
      - database_volume:/db/
      - .:/code
    ports:
      - 8000:8000
    env_file:
     - .env.dev

volumes:
  database_volume: {}